/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Placement */
        post: operations["create_placement_api_placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practices */
        get: operations["list_practices_api_practices_get"];
        put?: never;
        /** Create Practice */
        post: operations["create_practice_api_practices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar */
        get: operations["similar_api_practices_similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice */
        get: operations["get_practice_api_practices__practice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Practice */
        patch: operations["update_practice_api_practices__practice_id__patch"];
        trace?: never;
    };
    "/api/practices/{practice_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Practice */
        post: operations["archive_practice_api_practices__practice_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Practice */
        post: operations["restore_practice_api_practices__practice_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frames */
        get: operations["get_frames_api_radar_frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["list_revisions_api_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisions/{revision_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert */
        post: operations["revert_api_revisions__revision_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_teams__team_id__patch"];
        trace?: never;
    };
    "/api/teams/{team_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Team */
        post: operations["archive_team_api_teams__team_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/notes/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Note */
        get: operations["get_note_api_teams__team_id__notes__practice_id__get"];
        /** Put Note */
        put: operations["put_note_api_teams__team_id__notes__practice_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Team */
        post: operations["restore_team_api_teams__team_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FrameOut */
        FrameOut: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Points */
            points: components["schemas"]["PointOut"][];
        };
        /** FramesOut */
        FramesOut: {
            /** Frames */
            frames: components["schemas"]["FrameOut"][];
            /** Practices */
            practices: {
                [key: string]: components["schemas"]["PracticeRef"];
            };
            /** Scope */
            scope: string;
            /**
             * Step
             * @enum {string}
             */
            step: "week" | "month";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Link */
        Link: {
            /** Label */
            label: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Body Md */
            body_md: string;
            /** Edited By */
            edited_by: string | null;
            /** Practice Id */
            practice_id: number;
            /** Team Id */
            team_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** NotePut */
        NotePut: {
            /** Body Md */
            body_md: string;
            /** Version */
            version: number;
        };
        /** PlacementCreate */
        PlacementCreate: {
            /** Adoption */
            adoption?: number | null;
            /** Effective At */
            effective_at?: string | null;
            /** Practice Id */
            practice_id: number;
            /**
             * Removed
             * @default false
             */
            removed?: boolean;
            /** Team Id */
            team_id: number;
            /** Value */
            value?: number | null;
        };
        /** PlacementOut */
        PlacementOut: {
            /** Adoption */
            adoption: number;
            /** Edited By */
            edited_by: string | null;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Id */
            id: number;
            /** Practice Id */
            practice_id: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Removed */
            removed: boolean;
            /** Team Id */
            team_id: number;
            /** Value */
            value: number;
        };
        /** PointOut */
        PointOut: {
            /** Adoption */
            adoption: number;
            /** Practice Id */
            practice_id: number;
            /** Team Positions */
            team_positions?: components["schemas"]["TeamPositionOut"][] | null;
            /** Teams */
            teams: number;
            /** Value */
            value: number;
        };
        /** PracticeCreate */
        PracticeCreate: {
            /**
             * Body Md
             * @default
             */
            body_md?: string;
            /**
             * Category
             * @enum {string}
             */
            category: "tool" | "skill" | "practice" | "workflow";
            /**
             * Links
             * @default []
             */
            links?: components["schemas"]["Link"][];
            /** Name */
            name: string;
            /**
             * Summary
             * @default
             */
            summary?: string;
            /**
             * Tags
             * @default []
             */
            tags?: string[];
        };
        /** PracticeDetail */
        PracticeDetail: {
            /** Archived At */
            archived_at: string | null;
            /** Body Md */
            body_md: string;
            /**
             * Category
             * @enum {string}
             */
            category: "tool" | "skill" | "practice" | "workflow";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /** Teams */
            teams: components["schemas"]["PracticeTeamUsage"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** PracticeListItem */
        PracticeListItem: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "tool" | "skill" | "practice" | "workflow";
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /**
             * Teams Count
             * @default 0
             */
            teams_count?: number;
        };
        /** PracticeOut */
        PracticeOut: {
            /** Archived At */
            archived_at: string | null;
            /** Body Md */
            body_md: string;
            /**
             * Category
             * @enum {string}
             */
            category: "tool" | "skill" | "practice" | "workflow";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Links */
            links: components["schemas"]["Link"][];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** PracticeRef */
        PracticeRef: {
            /**
             * Category
             * @enum {string}
             */
            category: "tool" | "skill" | "practice" | "workflow";
            /** Name */
            name: string;
        };
        /** PracticeTeamUsage */
        PracticeTeamUsage: {
            /** Label */
            label: string;
            /** Note Md */
            note_md: string | null;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name: string;
            /** Team Slug */
            team_slug: string;
        };
        /** PracticeUpdate */
        PracticeUpdate: {
            /** Body Md */
            body_md?: string | null;
            /** Category */
            category?: ("tool" | "skill" | "practice" | "workflow") | null;
            /** Links */
            links?: components["schemas"]["Link"][] | null;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Version */
            version: number;
        };
        /** RevertOut */
        RevertOut: {
            /** Entity */
            entity: {
                [key: string]: unknown;
            };
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "team" | "practice" | "team_note";
        };
        /** RevisionOut */
        RevisionOut: {
            /** Action */
            action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Edited By */
            edited_by: string | null;
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "team" | "practice" | "team_note";
            /** Id */
            id: number;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
        };
        /** TeamCreate */
        TeamCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** TeamPositionOut */
        TeamPositionOut: {
            /** Adoption */
            adoption: number;
            /** Team Id */
            team_id: number;
            /** Value */
            value: number;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_placement_api_placements_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practices_api_practices_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("tool" | "skill" | "practice" | "workflow") | null;
                tag?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_api_practices_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_api_practices_similar_get: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_api_practices__practice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_practice_api_practices__practice_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_practice_api_practices__practice_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_practice_api_practices__practice_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frames_api_radar_frames_get: {
        parameters: {
            query?: {
                scope?: string;
                step?: "week" | "month";
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FramesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_revisions_get: {
        parameters: {
            query: {
                entity_type: "team" | "practice" | "team_note";
                entity_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_api_revisions__revision_id__revert_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                revision_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_api_teams_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_team_api_teams__team_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_api_teams__team_id__notes__practice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_note_api_teams__team_id__notes__practice_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                team_id: number;
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_team_api_teams__team_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "x-edited-by"?: string | null;
            };
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
